apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: staging cluster
  sourceRepos:
  - '*'
  destinations:
  - namespace: apps
    server: https://kubernetes.docker.internal:6443
