apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - url: https://github.com/s-tokutake/private-repo-sample
      name: samplerepo
      passwordSecret:
        name: private-repo-secret-token
        key: password
      usernameSecret:
        name: private-repo-secret-token
        key: username