apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prd-system
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destinations:
    - namespace: kube-system
      server: https://kubernetes.default.svc
  sourceRepos:
    - 'https://github.com/helm/charts.git'
    
