apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prd-podinfo
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: defualt
  project: production
  source:
    path: manifests
    repoURL: https://github.com/s-tokutake/argocd-demo.git
    targetRevision: production
  syncPolicy:
    automated:
      automated:
        prune: false
        selfHeal: false
      prune: true